export type FleetPhotoSource = {
  vehicle: string;
  year: number;
  generation: string;
  author: string;
  sourceUrl: string;
  license: string;
  licenseUrl: string;
  localPath: string;
  note: string;
};

export const FLEET_PHOTO_SOURCES: FleetPhotoSource[] = [
  {
    vehicle: "Renault Clio 4",
    year: 2018,
    generation: "IV facelift",
    author: "Vauxford",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:2018_Renault_Clio_Dynamique_S_NAV_TCE_900cc_Front.jpg",
    license: "CC BY-SA 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0",
    localPath: "/cars/renault-clio-4",
    note: "Clio IV, blank plate, outdoor. MODEL_YEAR_REVIEW_REQUIRED for 2019 listing.",
  },
  {
    vehicle: "Opel Corsa",
    year: 2023,
    generation: "F",
    author: "Alexander-93",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:2023_Opel_Corsa-e_IAA_2023_1X7A0385.jpg",
    license: "CC BY-SA 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0",
    localPath: "/cars/opel-corsa",
    note: "Last resort: indoor event, EV trim of Corsa F, Opel badge.",
  },
  {
    vehicle: "Peugeot 208",
    year: 2024,
    generation: "II phase 2",
    author: "Harvey Bold",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:2024_Peugeot_208_GT_PureTech_-_1200cc_1.2_(100PS)_Petrol_-_Agueda_Yellow_-_06-2024%2C_Front.jpg",
    license: "CC BY 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by/4.0",
    localPath: "/cars/peugeot-208",
    note: "Photographie Wikimedia Commons, convertie en WebP.",
  },
  {
    vehicle: "Citroën C3",
    year: 2023,
    generation: "III",
    author: "TourCoin",
    sourceUrl: "https://tourcoin.ma/cars/citroen-c3",
    license: "Photographie flotte",
    licenseUrl: "https://tourcoin.ma/photo-credits",
    localPath: "/cars/citroen-c3",
    note: "Photographie flotte client. Plaque non lisible.",
  },
  {
    vehicle: "Volkswagen Polo",
    year: 2019,
    generation: "VI pre-facelift",
    author: "Harvey Bold",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:2019_Volkswagen_Polo_SEL_TSI_-_999cc_1.0_(115PS)_Petrol_-_Flash_Red_-_03-2024%2C_Front.jpg",
    license: "CC BY 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by/4.0",
    localPath: "/cars/vw-polo",
    note: "Last resort: Polo VI pre-facelift, Harvey dealer-year plate.",
  },
  {
    vehicle: "Ford Fiesta",
    year: 2023,
    generation: "Mk7 facelift",
    author: "Harvey Bold",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:2023_Ford_Fiesta_Titanium_EcoBoost_-_999cc_1.0_(100PS)_Petrol_-_Agate_Black_-_02-2025%2C_Front.jpg",
    license: "CC0",
    licenseUrl: "https://creativecommons.org/publicdomain/zero/1.0/deed.en",
    localPath: "/cars/ford-fiesta",
    note: "Harvey Bold dealer-year plate, same policy as live 208.",
  },
  {
    vehicle: "Toyota Yaris",
    year: 2023,
    generation: "XP210",
    author: "Alexander Migl",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Toyota_Yaris_Hybrid_(XP210)_1X7A0353.jpg",
    license: "CC BY-SA 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0",
    localPath: "/cars/toyota-yaris",
    note: "Outdoor, plate not readable as a registration.",
  },
  {
    vehicle: "Hyundai i20",
    year: 2023,
    generation: "BC3",
    author: "TourCoin",
    sourceUrl: "https://tourcoin.ma/cars/hyundai-i20",
    license: "Photographie flotte",
    licenseUrl: "https://tourcoin.ma/photo-credits",
    localPath: "/cars/hyundai-i20",
    note: "Photographie flotte client. Plaque masquée.",
  },
  {
    vehicle: "Dacia Sandero",
    year: 2023,
    generation: "III",
    author: "Mihnea Lazăr",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Dacia_Sandero_2023_Front_1.jpg",
    license: "CC BY-SA 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0",
    localPath: "/cars/dacia-sandero",
    note: "Center of plate unreadable.",
  },
  {
    vehicle: "Volkswagen Golf",
    year: 2024,
    generation: "VIII",
    author: "Harvey Bold",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:2024_Volkswagen_Golf_R-Line_TSI_-_1498cc_1.5_(150PS)_Petrol_-_Reflex_Silver_-_02-2024%2C_Front.jpg",
    license: "CC BY 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by/4.0",
    localPath: "/cars/vw-golf",
    note: "Golf VIII hatch, no plate.",
  },
  {
    vehicle: "Renault Mégane",
    year: 2017,
    generation: "IV phase 1",
    author: "Vauxford",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:2017_Renault_Megane_Dynamique_S_NAV_DC_1.5_Front.jpg",
    license: "CC BY-SA 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0",
    localPath: "/cars/renault-megane",
    note: "Last resort: Mégane IV phase 1 blank plate; listing is 2024 phase 2 ICE.",
  },
  {
    vehicle: "Peugeot 308",
    year: 2023,
    generation: "III",
    author: "MoCars",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:2023_Peugeot_308_1.2_PureTech_GT_(Front_1).jpg",
    license: "CC0",
    licenseUrl: "https://creativecommons.org/publicdomain/zero/1.0/deed.en",
    localPath: "/cars/peugeot-308",
    note: "Gen III hatch, outdoor.",
  },
  {
    vehicle: "Opel Astra",
    year: 2022,
    generation: "L hatch",
    author: "Alexander Migl",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Opel_Astra_L_1X7A0351.jpg",
    license: "CC BY-SA 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0",
    localPath: "/cars/opel-astra",
    note: "No registration number; Auto Staiger frame only.",
  },
  {
    vehicle: "Citroën C4",
    year: 2022,
    generation: "III / C41",
    author: "Tokumeigakarinoaoshima",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Citro%C3%ABn_C4_SHINE_(3BA-C41HN05)_front.jpg",
    license: "CC BY-SA 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0",
    localPath: "/cars/citroen-c4",
    note: "Outdoor, blank plate, C4 III.",
  },
  {
    vehicle: "Toyota Corolla",
    year: 2024,
    generation: "E210 hatch",
    author: "Harvey Bold",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:2024_Toyota_Corolla_GR_Sport_HEV_-_1987cc_2.0_(196PS)_Petrol_Hybrid_-_Super_Green_-_07-2024%2C_Front.jpg",
    license: "CC BY 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by/4.0",
    localPath: "/cars/toyota-corolla",
    note: "Hatch, manufacturer plate.",
  },
  {
    vehicle: "Hyundai i30",
    year: 2021,
    generation: "PD facelift",
    author: "Harvey Bold",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:2021_Hyundai_i30_N_Line_T-GDi_-_1482cc_1.5_(159PS)_Petrol_-_Shadow_Grey_-_02-2025%2C_Front.jpg",
    license: "CC0",
    licenseUrl: "https://creativecommons.org/publicdomain/zero/1.0/deed.en",
    localPath: "/cars/hyundai-i30",
    note: "Harvey Bold dealer-year plate.",
  },
  {
    vehicle: "SEAT Leon",
    year: 2020,
    generation: "IV / KL",
    author: "Vauxford",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:2020_SEAT_Leon_FR_TSi_Evo_1.5_Front.jpg",
    license: "CC BY-SA 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0",
    localPath: "/cars/seat-leon",
    note: "Leon IV pre-facelift of listing year 2024.",
  },
  {
    vehicle: "Ford Focus",
    year: 2023,
    generation: "Mk4 facelift Active",
    author: "Harvey Bold",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:2023_Ford_Focus_Active_X_EcoBoost_-_999cc_1.0_(125PS)_Petrol_-_Moondust_Silver_-_02-2024%2C_Front.jpg",
    license: "CC BY 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by/4.0",
    localPath: "/cars/ford-focus",
    note: "Last resort: Active crossover body of Mk4 facelift.",
  },
  {
    vehicle: "Mercedes-Benz Classe A",
    year: 2018,
    generation: "W177 pre-facelift",
    author: "Vauxford",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:2018_Mercedes-Benz_A200_AMG_Line_Premium%2B_1.3_Front.jpg",
    license: "CC BY-SA 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0",
    localPath: "/cars/mercedes-benz-classe-a",
    note: "Last resort: W177 hatch, blank plate, pre-facelift vs 2024 listing.",
  },
  {
    vehicle: "Audi A3",
    year: 2022,
    generation: "8Y Sportback",
    author: "Harvey Bold",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:2022_Audi_A3_S_Line_35TFSI_-_1498cc_1.5_(150PS)_Petrol_-_Grey_-_04-2024%2C_Front.jpg",
    license: "CC BY 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by/4.0",
    localPath: "/cars/audi-a3",
    note: "8Y Sportback, blank plate.",
  },
  {
    vehicle: "Renault Mégane 4",
    year: 2017,
    generation: "IV phase 1",
    author: "Vauxford",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:2017_Renault_Megane_Dynamique_S_NAV_DC_1.5_Front.jpg",
    license: "CC BY-SA 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0",
    localPath: "/cars/renault-megane-4",
    note: "Same last-resort Mégane IV photo as Mégane 2024.",
  },
  {
    vehicle: "Renault Captur",
    year: 2020,
    generation: "II",
    author: "Vauxford",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:2020_Renault_Captur_S_Edition_Front.jpg",
    license: "CC BY-SA 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0",
    localPath: "/cars/renault-captur",
    note: "Captur II, plate not in frame.",
  },
  {
    vehicle: "Peugeot 2008",
    year: 2024,
    generation: "II facelift",
    author: "MoCars",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:2024_Peugeot_2008_PureTech_130_Allure_(Front).jpg",
    license: "CC0",
    licenseUrl: "https://creativecommons.org/publicdomain/zero/1.0/deed.en",
    localPath: "/cars/peugeot-2008",
    note: "Last resort: showroom, manufacturer plate.",
  },
  {
    vehicle: "Volkswagen T-Cross",
    year: 2023,
    generation: "I facelift",
    author: "Alexander-93",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Volkswagen_T-Cross_(2023)_1X7A2499.jpg",
    license: "CC BY-SA 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0",
    localPath: "/cars/volkswagen-t-cross",
    note: "Last resort: dealer display plate, not a registration.",
  },
  {
    vehicle: "Volkswagen T-Roc",
    year: 2024,
    generation: "I phase 2",
    author: "Harvey Bold",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:2024_Volkswagen_T-Roc_R-Line_TSI_-_1498cc_1.5_(150PS)_Petrol_-_Kings_Red_-_03-2024%2C_Front.jpg",
    license: "CC BY 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by/4.0",
    localPath: "/cars/volkswagen-t-roc",
    note: "Photographie Wikimedia Commons, convertie en WebP.",
  },
  {
    vehicle: "Hyundai Kona",
    year: 2024,
    generation: "SX2",
    author: "MercurySable99",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:2024_Hyundai_Kona_SEL%2C_front_right%2C_05-18-2024.jpg",
    license: "CC BY-SA 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0",
    localPath: "/cars/hyundai-kona",
    note: "No plate.",
  },
  {
    vehicle: "Dacia Duster",
    year: 2024,
    generation: "III",
    author: "Alexander-93",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Dacia_Duster_III_IMG_8961.jpg",
    license: "CC BY-SA 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0",
    localPath: "/cars/dacia-duster",
    note: "Photographie Wikimedia Commons, convertie en WebP.",
  },
  {
    vehicle: "Peugeot 508",
    year: 2019,
    generation: "II fastback",
    author: "Vauxford",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:2019_Peugeot_508_GT-Line_BlueHDi_1.5_(130_PS)_Front_(1).jpg",
    license: "CC BY-SA 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0",
    localPath: "/cars/peugeot-508",
    note: "508 II sedan/fastback, blank plate.",
  },
  {
    vehicle: "Volkswagen Passat",
    year: 2024,
    generation: "B9 wagon",
    author: "Alexander-93",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Volkswagen_Passat_Variant_B9_1X7A1960.jpg",
    license: "CC BY-SA 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0",
    localPath: "/cars/volkswagen-passat",
    note: "Europe 2024 Passat is B9 wagon.",
  },
  {
    vehicle: "Hyundai Elantra",
    year: 2024,
    generation: "CN7 facelift",
    author: "BuickRiviera99",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:2024_Hyundai_Elantra_SEL%2C_front_right%2C_07-25-2026.jpg",
    license: "CC BY-SA 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0",
    localPath: "/cars/hyundai-elantra",
    note: "No plate.",
  },
  {
    vehicle: "Honda Accord",
    year: 2024,
    generation: "CY",
    author: "MercurySable99",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:2024_Honda_Accord_EX%2C_front_left%2C_03-21-2026.jpg",
    license: "CC BY-SA 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0",
    localPath: "/cars/honda-accord",
    note: "No plate.",
  },
  {
    vehicle: "Mercedes-Benz Classe C",
    year: 2023,
    generation: "W206",
    author: "HJUdall",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:23_Mercedes-Benz_C300_4Matic.jpg",
    license: "CC0",
    licenseUrl: "https://creativecommons.org/publicdomain/zero/1.0/deed.en",
    localPath: "/cars/mercedes-benz-classe-c",
    note: "Photographie Wikimedia Commons, convertie en WebP.",
  },
  {
    vehicle: "Mercedes-Benz Classe E",
    year: 2023,
    generation: "W214",
    author: "Alexander-93",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Mercedes-Benz_W214_IAA_2023_1X7A0270.jpg",
    license: "CC BY-SA 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0",
    localPath: "/cars/mercedes-classe-e",
    note: "Last resort: indoor event, manufacturer plate.",
  },
  {
    vehicle: "Renault Austral",
    year: 2024,
    generation: "I",
    author: "Vauxford",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:2024_Renault_Austral_Techno_Esprit_Alpine_HEV_Automatic_1.2_Front.jpg",
    license: "CC BY-SA 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0",
    localPath: "/cars/renault-austral",
    note: "Last resort: showroom, manufacturer plate.",
  },
  {
    vehicle: "Peugeot 3008",
    year: 2021,
    generation: "II",
    author: "Tokumeigakarinoaoshima",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Peugeot_3008_GT_HYBRID4_(3LA-P845G06H)_front.jpg",
    license: "CC BY-SA 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0",
    localPath: "/cars/peugeot-3008",
    note: "Last resort: indoor, gen II ICE/PHEV matching essence listing not gen III EV.",
  },
  {
    vehicle: "Opel Mokka",
    year: 2021,
    generation: "B",
    author: "DanielPrzygoda",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Opel-mokka-e-vorne.jpg",
    license: "CC BY-SA 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0",
    localPath: "/cars/opel-mokka",
    note: "Last resort: studio/showroom, EV trim of Mokka B, Opel badge.",
  },
  {
    vehicle: "Volkswagen Tiguan",
    year: 2024,
    generation: "III",
    author: "Tokumeigakarinoaoshima",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Volkswagen_TIGUAN_eTSI_R-Line_(3AA-CT15)_front.jpg",
    license: "CC0",
    licenseUrl: "https://creativecommons.org/publicdomain/zero/1.0/deed.en",
    localPath: "/cars/volkswagen-tiguan",
    note: "Last resort: showroom gen III; small windshield paper overlay.",
  },
  {
    vehicle: "SEAT Arona",
    year: 2021,
    generation: "I facelift",
    author: "Calreyn88",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:2021_Seat_Arona_FR.jpg",
    license: "CC BY-SA 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0",
    localPath: "/cars/seat-arona",
    note: "No plate.",
  },
  {
    vehicle: "Dacia Bigster",
    year: 2025,
    generation: "I",
    author: "Alexander Migl",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Dacia_Bigster_DSC_8452.jpg",
    license: "CC BY-SA 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0",
    localPath: "/cars/dacia-bigster",
    note: "Manufacturer plate.",
  },
  {
    vehicle: "Hyundai Tucson",
    year: 2024,
    generation: "NX4 SWB phase 2",
    author: "Alexander-93",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Hyundai_Tucson_(NX4%2C_SWB)_N_Line_Facelift_Leonberg_2024_IMG_1077.jpg",
    license: "CC BY-SA 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0",
    localPath: "/cars/hyundai-tucson",
    note: "Photographie Wikimedia Commons, convertie en WebP.",
  },
  {
    vehicle: "Kia Sportage",
    year: 2023,
    generation: "NQ5",
    author: "Harvey Bold",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:2023_KIA_Sportage_GT-Line_T-GDi_-_1598cc_1.6_(226PS)_Petrol_Hybrid_-_Lemon_Splash_-_02-2024%2C_Front.jpg",
    license: "CC BY 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by/4.0",
    localPath: "/cars/kia-sportage",
    note: "NQ5, Harvey dealer-year plate; listing 2025 facelift same gen.",
  },
  {
    vehicle: "Ford Kuga",
    year: 2024,
    generation: "III facelift",
    author: "Harvey Bold",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:2024_Ford_Kuga_Active_Hybrid_AWD_-_2488cc_2.5_(183PS)_Hybrid_-_Desert_Island_Blue_-_10-2024%2C_Front.jpg",
    license: "CC0",
    licenseUrl: "https://creativecommons.org/publicdomain/zero/1.0/deed.en",
    localPath: "/cars/ford-kuga",
    note: "Harvey dealer-year plate.",
  }
];
